import {createRequire} from 'node:module';
import {readFile,readdir,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {randomBytes,pbkdf2Sync,createHmac,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.resolve('wrangler/package.json'));
const {Miniflare}=require('miniflare');
const server=path.resolve('dist/server');
const moduleFiles=(await readdir(server,{recursive:true})).filter(f=>f.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:a.localeCompare(b));
const adminPassword=randomBytes(20).toString('hex');const salt=randomBytes(32).toString('hex');
const config={DEMO_MODE:'true',APP_ORIGIN:'http://studio.test',APP_SECRET:randomBytes(32).toString('hex'),QUEUE_SECRET:randomBytes(32).toString('hex'),ADMIN_EMAIL:'admin@studio.test',ADMIN_PASSWORD_HASH:'pbkdf2$100000$'+salt+'$'+pbkdf2Sync(adminPassword,salt,100000,32,'sha256').toString('hex'),STRIPE_WEBHOOK_SECRET:'whsec_disposable_fixture'};
const options={modules:moduleFiles.map(f=>({type:'ESModule',path:path.join(server,f)})),modulesRoot:server,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],bindings:config,d1Databases:{DB:'studio-integration'},r2Buckets:['BUCKET'],cf:false};
const mf=new Miniflare(options);const checks=[];let fixture=0;
function ok(name,value){assert(value,name);checks.push({name,passed:true});console.log('PASS',name)}
async function request(route,{method='GET',data,cookie,headers={},expected=200}={}){const h={origin:config.APP_ORIGIN,...(cookie?{cookie}:{}),...(data&&!(data instanceof FormData)?{'content-type':'application/json'}:{}),...headers};let payload=data!==undefined?JSON.stringify(data):undefined;if(data instanceof FormData){const encoded=new Request(config.APP_ORIGIN+route,{method:'POST',body:data});h['content-type']=encoded.headers.get('content-type');payload=await encoded.arrayBuffer();}const response=await mf.dispatchFetch(config.APP_ORIGIN+route,{method,headers:h,body:payload});const text=await response.text();let body;try{body=JSON.parse(text)}catch{body=text}if(expected!==null)assert.equal(response.status,expected,`${method} ${route}: ${text.slice(0,350)}`);return {response,body,text,cookie:response.headers.get('set-cookie')?.split(';')[0]};}
async function upload(cookie,name='photo.webp',bytes){const form=new FormData();form.append('file',new File([bytes||await readFile('public/media/formula-driver.webp')],name,{type:name.endsWith('.txt')?'text/plain':'image/webp'}));return request('/api/uploads',{method:'POST',data:form,cookie,expected:name.endsWith('.txt')?415:201})}
async function checkout(cookie,template,uploadIds,price=template.price,key=randomUUID()){const payload={templateId:template.id,uploadIds,idempotencyKey:key,expectedPrice:price,consent:true};const r=await request('/api/checkout',{method:'POST',cookie,data:payload,expected:201});return {...r,payload};}
async function waitDone(cookie,id){const until=Date.now()+26000;const statuses=[];while(Date.now()<until){await request('/api/queue/tick',{method:'POST',cookie,data:{}});const r=await request('/api/generations/'+id,{cookie});const g=r.body.generations[0];statuses.push(g.status);if(['completed','failed'].includes(g.status))return {g,statuses};await new Promise(r=>setTimeout(r,1100));}throw new Error('Generation did not finish within 26s');}
try{
 const db=await mf.getD1Database('DB');const bucket=await mf.getR2Bucket('BUCKET');
 for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort()){for(const s of (await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(s).run();}
 const list=await request('/api/templates');const templates=list.body.templates;const formula=templates.find(t=>t.slug==='formula-driver');ok('18 seeded templates with fixed prices',templates.length===18&&formula.price===299&&new Set(templates.map(t=>t.price)).size>=5);
 ok('Public API hides prompts, providers, and costs',!list.text.includes('hiddenPrompt')&&!list.text.includes('estimatedCost')&&!list.text.includes('provider')&&!list.text.includes('workflow'));
 for(const route of ['/','/explore','/template/formula-driver','/template/wedding-cinematic','/privacy','/terms','/login','/register','/creations','/favorites','/orders','/account','/admin']){const r=await request(route);ok('Route loads: '+route,typeof r.body==='string'&&r.body.includes('PROJECT'));}
 await request('/template/does-not-exist',{expected:404});await request('/missing-route',{expected:404});ok('Missing templates and routes return 404',true);
 await request('/api/admin/templates',{expected:401});ok('Admin API rejects anonymous access',true);
 const reg=await request('/api/auth/register',{method:'POST',data:{name:'Disposable QA User',email:'qa@studio.test',password:'Test-password-123'},expected:201});const userCookie=reg.cookie;ok('Registration creates a secure session',!!userCookie&&reg.response.headers.get('set-cookie').includes('HttpOnly')&&reg.response.headers.get('set-cookie').includes('SameSite=Lax'));
 const userId=reg.body.user.id;await request('/api/admin/templates',{cookie:userCookie,expected:403});ok('Regular user cannot access admin API',true);
 await request('/api/auth/login',{method:'POST',data:{email:'qa@studio.test',password:'Incorrect-123'},expected:401});ok('Wrong password is rejected',true);
 const login=await request('/api/auth/login',{method:'POST',data:{email:'qa@studio.test',password:'Test-password-123'}});ok('Email login works',!!login.cookie);
 const second=await request('/api/auth/register',{method:'POST',data:{name:'Other User',email:'other@studio.test',password:'Other-password-123'},expected:201});
 await upload(userCookie,'fake.txt',new Uint8Array(40));ok('Unsupported file format rejected',true);
 const fake=new FormData();fake.append('file',new File([new Uint8Array(64)],'fake.webp',{type:'image/webp'}));await request('/api/uploads',{method:'POST',cookie:userCookie,data:fake,expected:415});ok('Forged image MIME rejected',true);
 const huge=new FormData();huge.append('file',new File([new Uint8Array(8*1024*1024+1)],'large.webp',{type:'image/webp'}));await request('/api/uploads',{method:'POST',cookie:userCookie,data:huge,expected:413});ok('Oversized upload rejected',true);
 const u=await upload(userCookie);ok('Valid upload is stored',u.body.id&&u.body.url.startsWith('/api/media/'));
 const media=await mf.dispatchFetch(config.APP_ORIGIN+u.body.url,{headers:{cookie:userCookie}});ok('Owner can view uploaded image',media.status===200&&media.headers.get('content-type')==='image/webp');await media.arrayBuffer();
 await request(u.body.url,{cookie:second.cookie,expected:403});await request(u.body.url,{expected:403});ok('Other users and anonymous visitors cannot read uploads',true);
 await request('/api/favorites',{method:'POST',cookie:userCookie,data:{templateId:formula.id}});const f=await request('/api/favorites',{cookie:userCookie});ok('Favorite persists server-side',f.body.ids.includes(formula.id));await request('/api/favorites',{method:'POST',cookie:userCookie,data:{templateId:formula.id}});ok('Favorite can be removed',(await request('/api/favorites',{cookie:userCookie})).body.ids.length===0);
 await request('/api/checkout',{method:'POST',cookie:second.cookie,data:{templateId:formula.id,uploadIds:[u.body.id],idempotencyKey:randomUUID(),expectedPrice:299,consent:true},expected:403});ok('Checkout rejects someone else’s image',true);
 await request('/api/checkout',{method:'POST',cookie:userCookie,data:{templateId:formula.id,uploadIds:[u.body.id],idempotencyKey:randomUUID(),expectedPrice:1,consent:true},expected:409});ok('Client cannot tamper with the price',true);
 const co=await checkout(userCookie,formula,[u.body.id]);const orderId=co.body.orderId,generationId=co.body.generationId;
 const duplicate=await request('/api/checkout',{method:'POST',cookie:userCookie,data:co.payload});ok('Checkout idempotency returns the same generation',duplicate.body.generationId===generationId);
 const pending=(await request('/api/generations/'+generationId,{cookie:userCookie})).body.generations[0];ok('Generation waits for payment',pending.status==='awaiting_payment');await request('/api/queue/tick',{method:'POST',cookie:userCookie,data:{}});ok('Queue cannot start unpaid work',(await request('/api/generations/'+generationId,{cookie:userCookie})).body.generations[0].status==='awaiting_payment');
 await request('/api/orders/'+orderId+'/pay',{method:'POST',cookie:second.cookie,data:{result:'success'},expected:404});ok('Payment confirmation enforces order ownership',true);
 await request('/api/orders/'+orderId+'/pay',{method:'POST',cookie:userCookie,data:{result:'fail'},expected:402});ok('Declined payment does not start generation',(await request('/api/generations/'+generationId,{cookie:userCookie})).body.generations[0].status==='awaiting_payment');
 await request('/api/orders/'+orderId+'/retry',{method:'POST',cookie:userCookie,data:{}});await request('/api/orders/'+orderId+'/pay',{method:'POST',cookie:userCookie,data:{result:'success'}});await request('/api/orders/'+orderId+'/pay',{method:'POST',cookie:userCookie,data:{result:'success'}});ok('Payment retry and duplicate confirmation are safe',true);
 const result=await waitDone(userCookie,generationId);ok('Mock workflow completes asynchronously',result.g.status==='completed'&&!!result.g.assetId);ok('Generations retain their paid price',result.g.price===299);
 const outputs=await db.prepare('SELECT * FROM generated_assets WHERE generation_id=?').bind(generationId).all();ok('Duplicate payment created one output only',outputs.results.length===1);
 const video=await mf.dispatchFetch(config.APP_ORIGIN+'/api/media/'+result.g.assetId+'?download=1',{headers:{cookie:userCookie}});const bytes=new Uint8Array(await video.arrayBuffer());ok('Download returns a real MP4 attachment',video.status===200&&video.headers.get('content-disposition').includes('attachment')&&new TextDecoder().decode(bytes.slice(4,8))==='ftyp');await mkdir('test-results',{recursive:true});await writeFile('test-results/download.mp4',bytes);
 const ranged=await mf.dispatchFetch(config.APP_ORIGIN+'/api/media/'+result.g.assetId,{headers:{cookie:userCookie,range:'bytes=0-99'}});ok('Video byte ranges are supported',ranged.status===206&&(await ranged.arrayBuffer()).byteLength===100);
 await request('/api/media/'+result.g.assetId,{cookie:second.cookie,expected:403});ok('Completed videos stay private',true);
 const share=await request('/api/generations/'+generationId+'/share',{method:'POST',cookie:userCookie,data:{}});const shared=await mf.dispatchFetch(share.body.url);ok('Signed share link works without account login',shared.status===200);await shared.arrayBuffer();const broken=new URL(share.body.url);broken.searchParams.set('signature','bad');await request(broken.pathname+broken.search,{expected:403});ok('Tampered share link is rejected',true);
 const adm=await request('/api/auth/login',{method:'POST',data:{email:'admin@studio.test',password:adminPassword}});const adminCookie=adm.cookie;ok('Administrator login succeeds',adm.body.user.role==='admin');
 const privateTemplate=(await request('/api/admin/templates/'+formula.id,{cookie:adminCookie})).body.template;ok('Admin can read hidden workflow',privateTemplate.workflow.length===1&&privateTemplate.hiddenPrompt.length>0);
 const clone={...privateTemplate,id:undefined,name:'QA Studio Test',slug:'qa-studio-test',active:false,price:449,estimatedCost:125,createdAt:undefined};const created=await request('/api/admin/templates',{method:'POST',cookie:adminCookie,data:clone,expected:201});let testTemplate=created.body.template;ok('Admin creates a template draft',!!testTemplate.id&&!testTemplate.active);
 ok('Draft is hidden from catalog',!(await request('/api/templates')).body.templates.some(t=>t.id===testTemplate.id));
 testTemplate={...testTemplate,active:true};await request('/api/admin/templates/'+testTemplate.id,{method:'PATCH',cookie:adminCookie,data:testTemplate});const publicNew=(await request('/api/templates')).body.templates.find(t=>t.id===testTemplate.id);ok('Published template appears immediately with chosen price',publicNew?.price===449);
 await request('/api/admin/templates/'+formula.id,{method:'PATCH',cookie:adminCookie,data:{...privateTemplate,price:449}});ok('Admin price update reaches the public catalog',(await request('/api/templates')).body.templates.find(t=>t.id===formula.id).price===449);ok('Price update does not rewrite paid orders',(await request('/api/orders/'+orderId,{cookie:userCookie})).body.order.amount===299);
 const another=await upload(userCookie);const unpaid=await checkout(userCookie,testTemplate,[another.body.id]);
 const imageStep={...testTemplate.workflow[0],id:randomUUID(),type:'image',output:'prepared_image'};const videoStep={...testTemplate.workflow[0],id:randomUUID(),inputs:{image:'{{previous_output}}'},output:'final_video'};
 testTemplate={...testTemplate,workflow:[imageStep,videoStep]};await request('/api/admin/templates/'+testTemplate.id,{method:'PATCH',cookie:adminCookie,data:testTemplate});ok('Admin saves ordered multi-step workflow',(await request('/api/admin/templates/'+testTemplate.id,{cookie:adminCookie})).body.template.workflow.length===2);
 const snap=await db.prepare('SELECT workflow_snapshot FROM generations WHERE id=?').bind(unpaid.body.generationId).first();ok('Existing checkout keeps the original workflow',JSON.parse(snap.workflow_snapshot).steps.length===1);
 const multi=await checkout(userCookie,testTemplate,[another.body.id]);await request('/api/orders/'+multi.body.orderId+'/pay',{method:'POST',cookie:userCookie,data:{result:'success'}});const mr=await waitDone(userCookie,multi.body.generationId);ok('Image-to-video workflow completes',mr.g.status==='completed');const logs=await db.prepare('SELECT * FROM generation_steps WHERE generation_id=? ORDER BY step_order').bind(multi.body.generationId).all();ok('Workflow steps execute in order',logs.results.length===2&&logs.results.every(s=>s.status==='completed'));
 const failedTemplate={...testTemplate,workflow:[{...videoStep,inputs:{image:'{{user_image_1}}'},settings:{simulateFailure:true}}]};await request('/api/admin/templates/'+testTemplate.id,{method:'PATCH',cookie:adminCookie,data:failedTemplate});const failure=await checkout(userCookie,failedTemplate,[another.body.id]);await request('/api/orders/'+failure.body.orderId+'/pay',{method:'POST',cookie:userCookie,data:{result:'success'}});const fr=await waitDone(userCookie,failure.body.generationId);ok('Provider failure is recorded',fr.g.status==='failed');ok('Failed generation is automatically refunded',(await request('/api/orders/'+failure.body.orderId,{cookie:userCookie})).body.order.status==='refunded');
 const dashboard=(await request('/api/admin/dashboard',{cookie:adminCookie})).body;ok('Admin metrics reflect real database activity',dashboard.users===3&&dashboard.metrics.total>=4&&dashboard.metrics.failed>=1);
 await request('/api/admin/users/'+second.body.user.id,{method:'PATCH',cookie:adminCookie,data:{status:'suspended'}});await request('/api/favorites',{cookie:second.cookie,expected:401});ok('Suspending a user revokes sessions',true);await request('/api/admin/users/'+second.body.user.id,{method:'PATCH',cookie:adminCookie,data:{status:'active'}});ok('Admin can reactivate users',true);
 await request('/api/account',{method:'PATCH',cookie:userCookie,data:{name:'Updated QA'}});ok('Account changes persist',(await request('/api/me',{cookie:userCookie})).body.user.name==='Updated QA');
 await request('/api/account',{method:'PATCH',cookie:userCookie,headers:{origin:'https://evil.test','sec-fetch-site':'cross-site'},data:{name:'Evil'},expected:403});ok('Cross-site mutation blocked',true);
 await request('/api/webhooks/stripe',{method:'POST',data:{id:'forged'},expected:400});ok('Unsigned Stripe webhook rejected',true);
 // Exercise real HMAC verification and replay handling without contacting Stripe.
 const sp=await db.prepare('SELECT * FROM payments WHERE order_id=?').bind(unpaid.body.orderId).first();await db.prepare("UPDATE payments SET provider='stripe' WHERE id=?").bind(sp.id).run();
 const e={id:'evt_fixture_1',type:'checkout.session.completed',data:{object:{id:sp.provider_session_id,payment_status:'paid',payment_intent:'pi_fixture',amount_total:sp.amount,currency:sp.currency.toLowerCase(),metadata:{order_id:unpaid.body.orderId}}}};const timestamp=Math.floor(Date.now()/1000);const signature=createHmac('sha256',config.STRIPE_WEBHOOK_SECRET).update(timestamp+'.'+JSON.stringify(e)).digest('hex');
 for(let i=0;i<2;i++)await request('/api/webhooks/stripe',{method:'POST',data:e,headers:{'stripe-signature':`t=${timestamp},v1=${signature}`}});ok('Signed Stripe webhook confirms payment and tolerates replay',(await request('/api/orders/'+unpaid.body.orderId,{cookie:userCookie})).body.order.status==='paid');ok('Webhook event persisted once',(await db.prepare("SELECT COUNT(*) AS n FROM webhook_events WHERE id='evt_fixture_1'").first()).n===1);
 // Creation/file deletion proves bytes are removed, rather than merely hidden.
 const assetKey=outputs.results[0].storage_key;await request('/api/generations/'+generationId,{method:'DELETE',cookie:userCookie});ok('Delete creation removes the video from object storage',await bucket.get(assetKey)===null);await request('/api/media/'+result.g.assetId,{cookie:userCookie,expected:404});
 const orphan=await upload(userCookie);const orphanDb=await db.prepare('SELECT storage_key FROM user_uploads WHERE id=?').bind(orphan.body.id).first();await request('/api/uploads/'+orphan.body.id,{method:'DELETE',cookie:userCookie});ok('Delete upload removes stored bytes',await bucket.get(orphanDb.storage_key)===null);
 const dup=await request('/api/admin/templates/'+testTemplate.id+'/duplicate',{method:'POST',cookie:adminCookie,data:{},expected:201});ok('Admin duplicates a template as a draft',!dup.body.template.active&&dup.body.template.id!==testTemplate.id);await request('/api/admin/templates/'+dup.body.template.id,{method:'DELETE',cookie:adminCookie});ok('Admin removes a template',!(await request('/api/admin/templates',{cookie:adminCookie})).body.templates.some(t=>t.id===dup.body.template.id));
 const clean=await request('/api/auth/register',{method:'POST',data:{name:'Delete Test',email:'delete@studio.test',password:'Delete-password-123'},expected:201});const cleanUpload=await upload(clean.cookie);await request('/api/account',{method:'DELETE',cookie:clean.cookie,data:{password:'Delete-password-123'}});ok('Account deletion removes the user and uploads',!(await db.prepare('SELECT id FROM users WHERE id=?').bind(clean.body.user.id).first())&&!(await db.prepare('SELECT id FROM user_uploads WHERE id=?').bind(cleanUpload.body.id).first()));
 await request('/api/auth/logout',{method:'POST',cookie:userCookie,data:{}});await request('/api/favorites',{cookie:userCookie,expected:401});ok('Sign-out invalidates the session',true);
 await writeFile('test-results/integration.json',JSON.stringify({date:new Date().toISOString(),passed:checks.length,checks},null,2));console.log('\n'+checks.length+' integration checks passed.');
}catch(e){console.error('FAIL',e);await mkdir('test-results',{recursive:true});await writeFile('test-results/integration.json',JSON.stringify({date:new Date().toISOString(),passed:checks.length,error:String(e),checks},null,2));process.exitCode=1}finally{await mf.dispose()}
