'use client';
import {useState} from 'react';
import {Activity,ArrowUpRight,CheckCircle2,Clock,DollarSign,Film,Plus,RefreshCw,ShieldCheck,Users,AlertCircle,Search} from 'lucide-react';
import {toast} from 'sonner';
import {api,useAPI,Busy,ErrorBox,Loading,Pick,date} from './shared';
import {money,statusLabel} from '@/lib/contracts';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from './ui/table';
import {Pagination,PaginationContent,PaginationItem} from './ui/pagination';

export function Pager({pagination,onPage}:{pagination?:{page:number;pages:number;total:number};onPage:(page:number)=>void}){
 if(!pagination)return null;
 return <div className="data-pager"><span>{pagination.total} results · Page {pagination.page} of {pagination.pages}</span><Pagination className="m-0 w-auto" aria-label="Result pages"><PaginationContent><PaginationItem><button className="button secondary small" disabled={pagination.page<=1} onClick={()=>onPage(pagination.page-1)}>Previous</button></PaginationItem><PaginationItem><button className="button secondary small" disabled={pagination.page>=pagination.pages} onClick={()=>onPage(pagination.page+1)}>Next</button></PaginationItem></PaginationContent></Pagination></div>;
}
export function RecordSearch({value,onChange,placeholder='Search by name, email, or ID'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){
 return <label className="record-search"><Search size={17}/><input type="search" aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>;
}
function Header({title,description,children}:{title:string;description:string;children?:React.ReactNode}){
 return <div className="admin-heading"><div><span className="eyebrow">STUDIO MANAGEMENT</span><h1>{title}</h1><p>{description}</p></div>{children}</div>;
}
export function StudioDashboard(){
 const {data:d,error,loading,refresh}=useAPI('admin/dashboard');
 const [currency,setCurrency]=useState('USD');
 if(loading)return <Loading/>;if(error)return <ErrorBox message={error} retry={refresh}/>;
 const finance=d.financials.find((f:any)=>f.currency===currency)||{revenue:0,estimated_cost:0,paid_count:0,refunded_count:0,refunded_amount:0};
 const days=Array.from({length:30},(_,i)=>new Date(Date.now()-(29-i)*86400000).toISOString().slice(0,10));
 const chart=days.map(day=>({day,value:d.daily.find((v:any)=>v.day===day&&v.currency===currency)?.revenue||0}));
 const peak=Math.max(...chart.map(v=>v.value),100);
 const currencies=Array.from(new Set(['USD',...d.financials.map((f:any)=>f.currency)])) as string[];
 return <>
  <Header title="Your studio at a glance." description="The creative work. The business behind it."><a className="button primary small" href="/admin/templates/new"><Plus size={16}/>New template</a></Header>
  {d.demo&&<div className="admin-demo-note"><Film size={22}/><div><strong>Your development studio</strong><p>These are test purchases and sample videos. No real money is collected.</p></div><a href="/admin/operations" className="text-link">Service readiness <ArrowUpRight size={15}/></a></div>}
  {!d.demo&&!d.purchasingAvailable&&<div className="admin-demo-note"><ShieldCheck size={22}/><div><strong>Finish connecting your studio</strong><p>Production mode is on. Checkout stays closed until your services are configured.</p></div><a href="/admin/connections" className="text-link">Open Connections <ArrowUpRight size={15}/></a></div>}
  <div className="dashboard-period"><span>All-time overview</span><Pick label="Reporting currency" value={currency} onChange={setCurrency} options={currencies}/></div>
  <div className="metric-grid">{[
    ['Net revenue',money(finance.revenue,currency),'After full refunds',DollarSign],
    ['Total generations',d.metrics.total||0,(d.metrics.today||0)+' in the last 24 hours',Film],
    ['Registered creators',d.users,'Across the studio',Users],
    ['Estimated gross profit',money(finance.revenue-finance.estimated_cost,currency),'Includes estimated cost of refunded jobs',Activity],
  ].map(([label,value,note,Icon]:any)=><div className="metric-card" key={label}><div><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><p>{note}</p></div>)}</div>
  <div className="admin-two-columns"><section className="panel"><div className="panel-heading"><h2>Revenue over time</h2><span className="eyebrow">LAST 30 DAYS · {currency}</span></div>
    <div className="revenue-chart" role="img" aria-label={'Daily net revenue over the last 30 days in '+currency}><span className="chart-max">{money(peak,currency)}</span><div className="chart-bars">{chart.map(v=><div key={v.day} className="chart-bar-slot"><div className={'chart-bar '+(v.value?'has-value':'')} style={{height:Math.max(v.value?3:1,v.value/peak*100)+'%'}} title={v.day+': '+money(v.value,currency)}/></div>)}</div><div className="chart-axis"><span>{days[0]}</span><span>{days[29]}</span></div></div>
    <div className="finance-strip"><div><small>Average paid order</small><strong>{money(finance.paid_count?Math.round(finance.revenue/finance.paid_count):0,currency)}</strong></div><div><small>Estimated AI cost</small><strong>{money(finance.estimated_cost,currency)}</strong></div><div><small>Refunded</small><strong>{money(finance.refunded_amount,currency)}</strong></div></div><p className="panel-note">AI costs are estimates for started jobs. Figures exclude payment fees and tax. Currencies are never combined.</p>
  </section><section className="panel"><div className="panel-heading"><h2>Recent generations</h2><a href="/admin/generations">View all <ArrowUpRight size={14}/></a></div><div className="recent-list">{d.recent.map((g:any)=><div key={g.id}><span className="list-icon"><Film size={18}/></span><div><strong>{g.template_name}</strong><small>{g.email||'Deleted account'}</small></div><span className={'status '+g.status}>{statusLabel(g.status)}</span></div>)}</div>{!d.recent.length&&<div className="small-empty"><Film/><p>Your first creation will appear here.</p></div>}<div className="health-summary"><span><i className="status-dot green"/>{d.metrics.completed||0} completed</span><span><i className="status-dot red"/>{d.metrics.failed||0} failed</span><a href="/admin/operations">Operations <ArrowUpRight size={14}/></a></div></section></div>
  <div className="admin-two-columns"><section className="panel"><div className="panel-heading"><h2>Highest estimated profit</h2><span className="eyebrow">PER VIDEO</span></div><div className="profit-list">{d.profitable.filter((t:any)=>t.currency===currency).map((t:any,i:number)=><div key={t.name}><span className="rank">0{i+1}</span><div><strong>{t.name}</strong><div className="profit-bar"><span style={{width:Math.max(0,(t.price-t.estimated_cost)/t.price*100)+'%'}}/></div></div><b>{money(t.price-t.estimated_cost,t.currency)}</b></div>)}</div><a className="text-link" href="/admin/templates">Manage pricing <ArrowUpRight size={14}/></a></section><section className="panel"><div className="panel-heading"><h2>Top selling templates</h2></div>{d.top.length?<Table><TableHeader><TableRow><TableHead>Template</TableHead><TableHead>Paid orders</TableHead><TableHead>Revenue</TableHead></TableRow></TableHeader><TableBody>{d.top.filter((t:any)=>t.currency===currency).map((t:any)=><TableRow key={t.template_name+t.currency}><TableCell>{t.template_name}</TableCell><TableCell>{t.count}</TableCell><TableCell>{money(t.revenue,t.currency)}</TableCell></TableRow>)}</TableBody></Table>:<p className="panel-note">Complete a purchase to see your first sale.</p>}</section></div>
  <section className="panel"><div className="panel-heading"><h2>Recent payments</h2><a href="/admin/payments">View all <ArrowUpRight size={14}/></a></div><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Template</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead>Date</TableHead></TableRow></TableHeader><TableBody>{d.recentPayments.map((o:any)=><TableRow key={o.id}><TableCell>{o.email||'Deleted account'}</TableCell><TableCell>{o.template_name}</TableCell><TableCell>{money(o.amount,o.currency)}</TableCell><TableCell><span className={'status '+o.status}>{statusLabel(o.status)}</span></TableCell><TableCell>{date(o.created_at)}</TableCell></TableRow>)}</TableBody></Table>{!d.recentPayments.length&&<p className="panel-note">Orders will appear here as your studio grows.</p>}</section>
 </>;
}

export function OperationsPanel(){
 const {data:d,error,loading,refresh}=useAPI('admin/operations');const [busy,setBusy]=useState(false);
 if(loading)return <Loading/>;if(error)return <ErrorBox message={error} retry={refresh}/>;
 const active=d.queue.filter((q:any)=>['queued','preparing','generating','finalizing'].includes(q.status)).reduce((n:number,q:any)=>n+q.count,0);
 async function dispatch(){setBusy(true);try{const r=await api('admin/operations/dispatch','POST',{});toast.success('Checked '+r.processed+' queued jobs');await refresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <><Header title="Keep everything moving." description="Service readiness, queue activity, and issues that need your attention."><button className="button secondary small" onClick={()=>refresh()}><RefreshCw size={16}/>Refresh</button></Header>
  <div className="metric-grid">{[['Active jobs',active],['Waiting for payment',d.unpaid],['Refunds to review',d.refunds.length],['Stored media',(d.storage.bytes/1024/1024).toFixed(1)+' MB']].map(([label,value])=><div className="metric-card" key={label}><div><span>{label}</span><Activity size={16}/></div><strong>{value}</strong></div>)}</div>
  <div className="admin-two-columns"><section className="panel"><div className="panel-heading"><h2>Service readiness</h2><ShieldCheck size={19}/></div>{d.checks.map((check:any)=><div className="service-check" key={check.name}>{check.ready?<CheckCircle2 size={19} className="profit-positive"/>:<AlertCircle size={19} className="readiness-warning"/>}<div><strong>{check.name}</strong><small>{check.detail}</small></div></div>)}<p className="panel-note">Configuration checks do not make paid requests. Verify live checkout, email delivery, and provider output before accepting customers.</p></section>
  <section className="panel"><div className="panel-heading"><h2>Generation queue</h2><Clock size={18}/></div>{['awaiting_payment','queued','preparing','generating','finalizing','completed','failed'].map(status=><div className="readiness-row" key={status}><span>{statusLabel(status)}</span><strong>{d.queue.find((q:any)=>q.status===status)?.count||0}</strong></div>)}<p className="panel-note">Last queue activity: {d.heartbeat?new Date(d.heartbeat).toLocaleString():'No activity yet'}. A dedicated dispatcher keeps long jobs moving when users close the page.</p><button className="button secondary small" disabled={busy} onClick={dispatch}>{busy?<Busy/>:<RefreshCw size={16}/>}Run a queue check</button></section></div>
  <section className="panel"><div className="panel-heading"><h2>Needs attention</h2><a href="/admin/payments">Manage payments <ArrowUpRight size={14}/></a></div>{!d.stalled.length&&!d.refunds.length?<div className="operations-empty"><CheckCircle2/><div><strong>No operational issues detected.</strong><p>Stalled jobs and unresolved refunds will appear here.</p></div></div>:<div className="operations-issues">{d.refunds.map((r:any)=><div key={r.id}><AlertCircle size={18}/><div><strong>Refund {r.status} · {money(r.amount,r.currency)}</strong><p>{r.email||'Deleted account'} · {r.error||'Awaiting provider confirmation'}</p></div><a className="text-link" href={'/admin/payments?search='+encodeURIComponent(r.order_id)}>Review</a></div>)}{d.stalled.map((g:any)=><div key={g.id}><Clock size={18}/><div><strong>{g.template_name} · {statusLabel(g.status)}</strong><p>Processing for more than 10 minutes. The job has a 30-minute deadline.</p></div><a className="text-link" href={'/admin/generations?search='+g.id}>Inspect</a></div>)}</div>}</section>
  <div className="admin-two-columns"><section className="panel"><h2>Recent generation failures</h2>{d.failures.length?<div className="failure-list">{d.failures.map((g:any)=><div key={g.id}><strong>{g.template_name}</strong><span className={'status '+g.payment_status}>{statusLabel(g.payment_status)}</span><p>{g.internal_error||g.error}</p></div>)}</div>:<p>No failed jobs to review.</p>}</section><section className="panel"><h2>Product activity</h2><p>Recorded events over the last 30 days.</p>{d.events.map((e:any)=><div className="readiness-row" key={e.name}><span>{e.name.replaceAll('_',' ')}</span><strong>{e.count}</strong></div>)}{!d.events.length&&<p className="panel-note">Activity will appear as people use the studio.</p>}</section></div>
 </>;
}

export function ActivityPanel(){
 const [page,setPage]=useState(1),[search,setSearch]=useState('');
 const {data,error,loading,refresh}=useAPI('admin/activity?'+new URLSearchParams({page:String(page),search,limit:'25'}));
 return <><Header title="A clear record of changes." description="Template edits, refunds, account security, and administrative actions."/><div className="admin-toolbar"><RecordSearch value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="Search actions, email, or record ID"/></div>{loading?<Loading/>:error?<ErrorBox message={error} retry={refresh}/>:<><div className="table-panel"><Table><TableHeader><TableRow><TableHead>Action</TableHead><TableHead>Account</TableHead><TableHead>Record</TableHead><TableHead>Time</TableHead></TableRow></TableHeader><TableBody>{data.activity.map((a:any)=><TableRow key={a.id}><TableCell><strong>{a.action.replaceAll('.',' · ')}</strong></TableCell><TableCell>{a.email||'Removed account'}</TableCell><TableCell className="mono">{a.target_id}</TableCell><TableCell>{new Date(a.created_at).toLocaleString()}</TableCell></TableRow>)}</TableBody></Table>{!data.activity.length&&<div className="small-empty"><p>No matching activity.</p></div>}</div><Pager pagination={data.pagination} onPage={setPage}/></>}</>;
}
