'use client';
import type {ActivityPage,Dashboard,Operations} from '@/lib/api-types';
import type {LucideIcon} from 'lucide-react';
import {useState} from 'react';
import {Activity,ArrowUpRight,CheckCircle2,Clock,DollarSign,Film,Plus,RefreshCw,ShieldCheck,Users,AlertCircle,Search} from 'lucide-react';
import {toast} from 'sonner';
import {api,useAPI,Busy,ErrorBox,Loading,Pick,date} from './shared';
import {credits,money,statusLabel} from '@/lib/contracts';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from './ui/table';
import {Pagination,PaginationContent,PaginationItem} from './ui/pagination';

export function Pager({pagination,onPage}:{pagination?:{page:number;pages:number;total:number};onPage:(page:number)=>void}){
 if(!pagination)return null;
 return <div className="data-pager"><span>{pagination.total} results · Page {pagination.page} of {pagination.pages}</span><Pagination className="m-0 w-auto" aria-label="Result pages"><PaginationContent><PaginationItem><button className="button secondary small" disabled={pagination.page<=1} onClick={()=>onPage(pagination.page-1)}>Previous</button></PaginationItem><PaginationItem><button className="button secondary small" disabled={pagination.page>=pagination.pages} onClick={()=>onPage(pagination.page+1)}>Next</button></PaginationItem></PaginationContent></Pagination></div>;
}
export function RecordSearch({value,onChange,placeholder='Search by name, email, or ID'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){
 return <label className="record-search"><Search size={17}/><input type="search" aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>;
}
function Header({title,description,children}:{title:string;description:string;children?:React.ReactNode}){
 return <div className="admin-heading"><div><span className="eyebrow">STUDIO MANAGEMENT</span><h1>{title}</h1><p>{description}</p></div>{children}</div>;
}
export function StudioDashboard(){
 const {data:d,error,loading,refresh}=useAPI<Dashboard>('admin/dashboard');
 const [currency,setCurrency]=useState('USD');const [openedAt]=useState(()=>Date.now());
 if(loading||!d)return error?<ErrorBox message={error} retry={refresh}/>:<Loading/>;
 const finance=d.financials.find(f=>f.currency===currency)||{revenue:0,estimated_cost:0,paid_count:0,reversed_count:0,reversed_amount:0};
 const days=Array.from({length:30},(_,i)=>new Date(openedAt-(29-i)*86400000).toISOString().slice(0,10));
 const chart=days.map(day=>({day,value:d.daily.find(v=>v.day===day&&v.currency===currency)?.revenue||0}));
 const peak=Math.max(...chart.map(v=>v.value),100);
 const currencies=Array.from(new Set(['USD',...d.financials.map(f=>f.currency)]));
 return <>
  <Header title="Your studio at a glance." description="The creative work. The business behind it."><a className="button primary small" href="/admin/templates/new"><Plus size={16}/>New template</a></Header>
  {d.demo&&<div className="admin-demo-note"><Film size={22}/><div><strong>Your development studio</strong><p>Credit purchases use the test checkout and videos are samples. No real money is collected.</p></div><a href="/admin/operations" className="text-link">Service readiness <ArrowUpRight size={15}/></a></div>}
  {!d.demo&&!d.purchasingAvailable&&<div className="admin-demo-note"><ShieldCheck size={22}/><div><strong>Finish connecting your studio</strong><p>Production mode is on. Buying credits stays closed until payments, email, an AI provider and the dispatcher are configured.</p></div><a href="/admin/connections" className="text-link">Open Connections <ArrowUpRight size={15}/></a></div>}
  <div className="dashboard-period"><span>All-time overview</span><Pick label="Reporting currency" value={currency} onChange={setCurrency} options={currencies}/></div>
  <div className="metric-grid">{([
    ['Net revenue',money(finance.revenue,currency),'Credit packs sold, after reversed payments',DollarSign],
    ['Total generations',d.metrics.total||0,(d.metrics.today||0)+' in the last 24 hours',Film],
    ['Registered creators',d.users,'Across the studio',Users],
    ['Credits outstanding',credits(d.credits.outstanding),credits(d.credits.consumed)+' spent · '+credits(d.credits.sold)+' sold · '+credits(d.credits.granted)+' given',Activity],
  ] as [string,string|number,string,LucideIcon][]).map(([label,value,note,Icon])=><div className="metric-card" key={label}><div><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><p>{note}</p></div>)}</div>
  <div className="admin-two-columns"><section className="panel"><div className="panel-heading"><h2>Revenue over time</h2><span className="eyebrow">LAST 30 DAYS · {currency}</span></div>
    <div className="revenue-chart" role="img" aria-label={'Daily net revenue over the last 30 days in '+currency}><span className="chart-max">{money(peak,currency)}</span><div className="chart-bars">{chart.map(v=><div key={v.day} className="chart-bar-slot"><div className={'chart-bar '+(v.value?'has-value':'')} style={{height:Math.max(v.value?3:1,v.value/peak*100)+'%'}} title={v.day+': '+money(v.value,currency)}/></div>)}</div><div className="chart-axis"><span>{days[0]}</span><span>{days[29]}</span></div></div>
    <div className="finance-strip"><div><small>Average purchase</small><strong>{money(finance.paid_count?Math.round(finance.revenue/finance.paid_count):0,currency)}</strong></div><div><small>Estimated AI cost</small><strong>{money(finance.estimated_cost,currency)}</strong></div><div><small>Reversed payments</small><strong>{money(finance.reversed_amount,currency)}</strong></div></div><p className="panel-note">Revenue is recognised when credits are sold; outstanding credits are still owed to customers. AI costs are estimates for started jobs. Figures exclude payment fees and tax. Currencies are never combined.</p>
  </section><section className="panel"><div className="panel-heading"><h2>Recent generations</h2><a href="/admin/generations">View all <ArrowUpRight size={14}/></a></div><div className="recent-list">{d.recent.map(g=><div key={g.id}><span className="list-icon"><Film size={18}/></span><div><strong>{g.template_name}</strong><small>{g.email||'Deleted account'}</small></div><span className={'status '+g.status}>{statusLabel(g.status)}</span></div>)}</div>{!d.recent.length&&<div className="small-empty"><Film/><p>Your first creation will appear here.</p></div>}<div className="health-summary"><span><i className="status-dot green"/>{d.metrics.completed||0} completed</span><span><i className="status-dot red"/>{d.metrics.failed||0} failed</span><a href="/admin/operations">Operations <ArrowUpRight size={14}/></a></div></section></div>
  <div className="admin-two-columns"><section className="panel"><div className="panel-heading"><h2>Highest estimated profit</h2><span className="eyebrow">PER VIDEO</span></div><div className="profit-list">{d.profitable.filter(t=>t.currency===currency).map((t,i)=><div key={t.name}><span className="rank">0{i+1}</span><div><strong>{t.name}</strong><div className="profit-bar"><span style={{width:Math.max(0,t.value?(t.value-t.estimated_cost)/t.value*100:0)+'%'}}/></div></div><b>{money(t.value-t.estimated_cost,t.currency)}</b></div>)}</div>{!d.profitable.some(t=>t.currency===currency)&&<p className="panel-note">Add a credit pack priced in {currency} to estimate margins.</p>}<a className="text-link" href="/admin/templates">Manage credit costs <ArrowUpRight size={14}/></a></section><section className="panel"><div className="panel-heading"><h2>Most used templates</h2></div>{d.top.length?<Table><TableHeader><TableRow><TableHead>Template</TableHead><TableHead>Videos</TableHead><TableHead>Credits spent</TableHead></TableRow></TableHeader><TableBody>{d.top.map(t=><TableRow key={t.template_name}><TableCell>{t.template_name}</TableCell><TableCell>{t.count}</TableCell><TableCell>{credits(t.credits)}</TableCell></TableRow>)}</TableBody></Table>:<p className="panel-note">Delivered videos will appear here.</p>}</section></div>
  <section className="panel"><div className="panel-heading"><h2>Recent credit purchases</h2><a href="/admin/purchases">View all <ArrowUpRight size={14}/></a></div><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Pack</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead>Date</TableHead></TableRow></TableHeader><TableBody>{d.recentPurchases.map(o=><TableRow key={o.id}><TableCell>{o.email||'Deleted account'}</TableCell><TableCell>{o.package_name}<small className="block">{credits(o.credits)}</small></TableCell><TableCell>{money(o.amount,o.currency)}</TableCell><TableCell><span className={'status '+o.status}>{statusLabel(o.status)}</span></TableCell><TableCell>{date(o.created_at)}</TableCell></TableRow>)}</TableBody></Table>{!d.recentPurchases.length&&<p className="panel-note">Credit purchases will appear here as your studio grows.</p>}</section>
 </>;
}

export function OperationsPanel(){
 const {data:d,error,loading,refresh}=useAPI<Operations>('admin/operations');const [busy,setBusy]=useState(false);
 if(loading||!d)return error?<ErrorBox message={error} retry={refresh}/>:<Loading/>;
 const active=d.queue.filter(q=>['queued','preparing','generating','finalizing'].includes(q.status)).reduce((n,q)=>n+q.count,0);
 async function dispatch(){setBusy(true);try{const r=await api<{processed:number}>('admin/operations/dispatch','POST',{});toast.success('Checked '+r.processed+' queued jobs');await refresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <><Header title="Keep everything moving." description="Service readiness, queue activity, and issues that need your attention."><button className="button secondary small" onClick={()=>refresh()}><RefreshCw size={16}/>Refresh</button></Header>
  <div className="metric-grid">{[['Active jobs',active],['Credits reserved',credits(d.credits.held)],['Reversed purchases',d.reversals.length],['Stored media',(d.storage.bytes/1024/1024).toFixed(1)+' MB']].map(([label,value])=><div className="metric-card" key={label}><div><span>{label}</span><Activity size={16}/></div><strong>{value}</strong></div>)}</div>
  <div className="admin-two-columns"><section className="panel"><div className="panel-heading"><h2>Service readiness</h2><ShieldCheck size={19}/></div>{d.checks.map(check=><div className="service-check" key={check.name}>{check.ready?<CheckCircle2 size={19} className="profit-positive"/>:<AlertCircle size={19} className="readiness-warning"/>}<div><strong>{check.name}</strong><small>{check.detail}</small></div></div>)}<p className="panel-note">Configuration checks do not make paid requests. Verify live checkout, email delivery, and provider output before accepting customers.</p></section>
  <section className="panel"><div className="panel-heading"><h2>Generation queue</h2><Clock size={18}/></div>{['queued','preparing','generating','finalizing','completed','failed','refused'].map(status=><div className="readiness-row" key={status}><span>{statusLabel(status)}</span><strong>{d.queue.find(q=>q.status===status)?.count||0}</strong></div>)}<div className="readiness-row"><span>Background dispatcher</span><strong>{d.dispatchHeartbeat?new Date(d.dispatchHeartbeat).toLocaleString()+(d.dispatchSource==='cron'?' · cron':' · external'):'Not running yet'}</strong></div><p className="panel-note">Last queue activity: {d.heartbeat?new Date(d.heartbeat).toLocaleString():'No activity yet'}. The live Worker runs the dispatcher every minute, so videos keep moving after customers close the page. If its last run is over three minutes old, buying credits and starting videos close until it runs again.</p><button className="button secondary small" disabled={busy} onClick={dispatch}>{busy?<Busy/>:<RefreshCw size={16}/>}Run a queue check</button></section></div>
  <section className="panel"><div className="panel-heading"><h2>Needs attention</h2><a href="/admin/purchases">Credit purchases <ArrowUpRight size={14}/></a></div>{!d.stalled.length&&!d.reversals.length?<div className="operations-empty"><CheckCircle2/><div><strong>No operational issues detected.</strong><p>Stalled jobs and reversed payments will appear here.</p></div></div>:<div className="operations-issues">{d.reversals.map(r=><div key={r.id}><AlertCircle size={18}/><div><strong>Payment reversed · {r.package_name} · {money(r.amount,r.currency)}</strong><p>{r.email||'Deleted account'} · {credits(r.credits)} removed · balance now {credits(r.balance)}</p></div><a className="text-link" href={'/admin/credits?search='+encodeURIComponent(r.id)}>Ledger</a></div>)}{d.stalled.map(g=><div key={g.id}><Clock size={18}/><div><strong>{g.template_name} · {statusLabel(g.status)}</strong><p>Processing for more than 10 minutes. The job has a 30-minute deadline.</p></div><a className="text-link" href={'/admin/generations?search='+g.id}>Inspect</a></div>)}</div>}</section>
  <div className="admin-two-columns"><section className="panel"><h2>Recent generation failures</h2>{d.failures.length?<div className="failure-list">{d.failures.map(g=><div key={g.id}><strong>{g.template_name}</strong>{g.credit_status&&<span className={'status '+(g.credit_status==='released'?'completed':'pending')}>{g.credit_status==='released'?'Credits returned':statusLabel(g.credit_status)}</span>}<p>{g.internal_error||g.error}</p></div>)}</div>:<p>No failed jobs to review.</p>}</section><section className="panel"><h2>Product activity</h2><p>Recorded events over the last 30 days.</p>{d.events.map(e=><div className="readiness-row" key={e.name}><span>{e.name.replaceAll('_',' ')}</span><strong>{e.count}</strong></div>)}{!d.events.length&&<p className="panel-note">Activity will appear as people use the studio.</p>}</section></div>
 </>;
}

export function ActivityPanel(){
 const [page,setPage]=useState(1),[search,setSearch]=useState('');
 const {data,error,loading,refresh}=useAPI<ActivityPage>('admin/activity?'+new URLSearchParams({page:String(page),search,limit:'25'}));
 return <><Header title="A clear record of changes." description="Template edits, refunds, account security, and administrative actions."/><div className="admin-toolbar"><RecordSearch value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="Search actions, email, or record ID"/></div>{loading?<Loading/>:error||!data?<ErrorBox message={error} retry={refresh}/>:<><div className="table-panel"><Table><TableHeader><TableRow><TableHead>Action</TableHead><TableHead>Account</TableHead><TableHead>Record</TableHead><TableHead>Time</TableHead></TableRow></TableHeader><TableBody>{data.activity.map(a=><TableRow key={a.id}><TableCell><strong>{a.action.replaceAll('.',' · ')}</strong></TableCell><TableCell>{a.email||'Removed account'}</TableCell><TableCell className="mono">{a.target_id}</TableCell><TableCell>{new Date(a.created_at).toLocaleString()}</TableCell></TableRow>)}</TableBody></Table>{!data.activity.length&&<div className="small-empty"><p>No matching activity.</p></div>}</div><Pager pagination={data.pagination} onPage={setPage}/></>}</>;
}
