'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Layers,CheckCircle2,LockKeyhole,Eye,EyeOff} from 'lucide-react';
import {api,Busy,ErrorBox,Field,safeNext} from './shared';
import {Checkbox} from '@/components/ui/checkbox';
import {MINIMUM_AGE} from '@/lib/contracts';
export function SignInGate({next='/creations',admin=false}:{next?:string;admin?:boolean}){return <div className="signin-gate"><span className="gate-icon"><LockKeyhole size={26}/></span><h1>{admin?'Your studio, behind the scenes.':'Your next creation starts here.'}</h1><p>{admin?'Sign in with your administrator account to manage templates, credits, and customers.':'Create an account to save your photos, make videos, and keep every creation in one place.'}</p><div className="button-row"><a className="button primary" href={'/login?next='+encodeURIComponent(next)}>Sign in <ArrowRight size={17}/></a>{!admin&&<a className="button secondary" href={'/register?next='+encodeURIComponent(next)}>Create account</a>}</div></div>}
export default function AuthPage({route,query,demo,registrationAvailable}:{route:string;query:Record<string,string|undefined>;demo:boolean;registrationAvailable:boolean}){
 const register=route==='/register',forgot=route==='/forgot-password',reset=route==='/reset-password',verify=route==='/verify',missingLink=(verify||reset)&&!query.token;const [email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(verify&&!!query.token),[error,setError]=useState(''),[done,setDone]=useState(false),[message,setMessage]=useState('');
 const [acceptTerms,setAcceptTerms]=useState(false),[confirmAge,setConfirmAge]=useState(false),[marketing,setMarketing]=useState(false),[showPassword,setShowPassword]=useState(false);
 useEffect(()=>{if(verify&&query.token){api('auth/verify','POST',{token:query.token}).then(()=>setDone(true)).catch(e=>setError(e.message)).finally(()=>setBusy(false))}},[verify,query.token]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(forgot){const r=await api<{message?:string}>('auth/forgot','POST',{email});setMessage(r.message||'If that account exists, a reset link is on its way.');setDone(true)}else if(reset){await api('auth/reset','POST',{password,token:query.token});setDone(true)}else{await api('auth/'+(register?'register':'login'),'POST',{email,password,...(register?{name,acceptTerms,confirmAge,marketingOptIn:marketing}:{})});window.location.assign(safeNext(query.next));}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="auth-layout"><div className="auth-art"><img src="/media/cyberpunk-city.webp" alt="Cinematic cyberpunk portrait"/><div><span className="eyebrow">ONE PHOTO. ENDLESS POSSIBILITIES.</span><h2>Your next story<br/>starts with you.</h2></div></div><div className="auth-form"><span className="mini-symbol"><Layers/></span><h1>{done?'You’re all set.':verify?'Verify your email':register?'Make room for a new you.':forgot?'Forgot your password?':reset?'A fresh start.':'Welcome back.'}</h1><p>{done?(forgot?message:reset?'Your password has been changed. Sign in with your new password.':'Your email is verified. You’re ready to create.'):register?'Create your account. Your main character moment is waiting.':forgot?'Enter your email and we’ll send you a reset link.':missingLink?(verify?'This verification link is incomplete. Open the link from your email again, or send a new one from your account.':'This reset link is incomplete. Open the link from your email again, or ask for a new one.'):reset?'Choose a new password with at least 10 characters.':verify?(busy?'Confirming your email address...':'This link could not verify your email. Send a new link from your account.'):'Your ideas, your creations, your studio.'}</p>{register&&!registrationAvailable&&<div className="subtle-note"><strong>Registration opens soon.</strong><p>You can explore the templates now. Existing members can still sign in.</p></div>}{error&&<ErrorBox message={error}/>} {done?<div className="auth-success"><CheckCircle2 size={34}/><a href={verify?'/creations':'/login'} className="button primary">{verify?'Start creating':'Back to sign in'} <ArrowRight size={17}/></a></div>:verify?(busy?<p><Busy>Verifying...</Busy></p>:<a className="button primary full" href="/account">Send a new link from your account <ArrowRight size={17}/></a>):missingLink?<a className="button primary full" href="/forgot-password">Ask for a new reset link <ArrowRight size={17}/></a>:<form onSubmit={submit}>{register&&<Field label="Your name"><input required autoComplete="name" placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/></Field>}{!reset&&<Field label="Email address"><input type="email" required autoComplete="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/></Field>}{!forgot&&<Field label="Password"><span className="password-field"><input type={showPassword?'text':'password'} required minLength={10} maxLength={128} autoComplete={register||reset?'new-password':'current-password'} placeholder="At least 10 characters" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="password-toggle" aria-label={showPassword?'Hide password':'Show password'} aria-pressed={showPassword} onClick={()=>setShowPassword(s=>!s)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></Field>}{register&&<div className="consent-group">
 <label className="consent"><Checkbox checked={acceptTerms} onCheckedChange={v=>setAcceptTerms(v===true)}/><span>I accept the <a href="/terms" target="_blank" rel="noreferrer">Terms</a> and <a href="/privacy" target="_blank" rel="noreferrer">Privacy Policy</a>.</span></label>
 <label className="consent"><Checkbox checked={confirmAge} onCheckedChange={v=>setConfirmAge(v===true)}/><span>I am {MINIMUM_AGE} years of age or older.</span></label>
 <label className="consent"><Checkbox checked={marketing} onCheckedChange={v=>setMarketing(v===true)}/><span>Send me news and offers by email. <small>Optional — you can unsubscribe anytime.</small></span></label>
</div>}{!register&&!forgot&&!reset&&<a className="forgot-link" href="/forgot-password">Forgot password?</a>}<button className="button primary full" disabled={busy||register&&!registrationAvailable||register&&(!acceptTerms||!confirmAge)}>{busy?<Busy/>:forgot?'Send reset link':reset?'Save password':register?'Create account':'Sign in'}{!busy&&<ArrowRight size={17}/>}</button></form>}{!done&&!verify&&!reset&&!forgot&&<p className="auth-switch">{register?'Already have an account?':'New around here?'} <a href={(register?'/login':'/register')+'?next='+encodeURIComponent(safeNext(query.next))}>{register?'Sign in':'Create an account'}</a></p>}{demo&&<div className="subtle-note"><span>DEMO STUDIO</span><p>Use any email to try the experience. Test payments never charge you. Demo videos use sample footage.</p></div>}{!register&&<p className="auth-legal">By continuing, you agree to our <a href="/terms">Terms</a> and <a href="/privacy">Privacy Policy</a>.</p>}</div></div>;
}
