'use client';
import {useState,useEffect,useMemo} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,ArrowRight,Play,Search,Heart,Sparkles,Film,Layers,Flame} from 'lucide-react';
import type {PublicTemplate} from '@/lib/contracts';
import {credits,approxPrice,categories as defaultCategories} from '@/lib/contracts';
import type {CreditRef} from '@/lib/contracts';
import {ALL_CATEGORIES,filtersFromQuery,filtersToQuery,heroTemplates,matchesTemplate,sortOptions,sortTemplates,tagOptions,type Sort,type Tag} from '@/lib/discovery';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';



export default function Discovery({route,query,data,favoriteIds,onFavorite}:{route:string;query:Record<string,string|undefined>;data:{templates:PublicTemplate[];creditRef?:CreditRef};favoriteIds:string[];onFavorite:(id:string)=>void}){
 const categories=useMemo(()=>Array.from(new Set([...defaultCategories,...data.templates.map(t=>t.category)])),[data.templates]);
 const [initial]=useState(()=>filtersFromQuery(query));
 const [category,setCategory]=useState(initial.category),[search,setSearch]=useState(initial.search),[sort,setSort]=useState<Sort>(initial.sort),[flag,setFlag]=useState<Tag>(initial.tag);
 // Keep the filters in the address bar so refresh, sharing, bookmarks and returning with Back restore them. Typing settles first.
 useEffect(()=>{const timer=setTimeout(()=>{const url=new URL(window.location.href);const next=filtersToQuery({category,search,tag:flag,sort},url.searchParams).toString();if(next!==url.searchParams.toString())window.history.replaceState(window.history.state,'',url.pathname+(next?'?'+next:'')+url.hash)},search===initial.search?0:350);return()=>clearTimeout(timer)},[category,search,flag,sort,initial.search]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'search_templates',description:'Filter the visible template catalog by search text and category. Does not purchase or generate.',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:categories}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){const v=input as {query?:unknown;category?:unknown};if(!v||typeof v.query!=='string'||v.query.length>200||v.category!==undefined&&!categories.includes(v.category as string))throw new Error('Invalid search or category');const q=v.query,c=typeof v.category==='string'?v.category:ALL_CATEGORIES;flushSync(()=>{setSearch(q);setCategory(c);setFlag('all')});return {templates:data.templates.filter(t=>matchesTemplate(t,{category:c,search:q,tag:'all'})).map(t=>({name:t.name,creditCost:t.creditCost,url:'/template/'+t.slug}))};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();},[data.templates,categories]);
 const shown=sortTemplates(data.templates.filter(t=>matchesTemplate(t,{category,search,tag:flag})),sort);
 // The front, center poster is the top recommendation.
 const [first,second,third]=heroTemplates(data.templates);
return <>{route==='/'&&<section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={14}/> A LITTLE YOU. A LOT OF POSSIBILITY.</span><h1>Your next<br/><em>main character</em><br/>moment.</h1><p>One photo. Endless possibilities.<br/>Pick a template and step into something new.</p><a href="#templates" className="button primary">Find your next look <ArrowUpRight size={18}/></a><div className="hero-note"><span><Film size={15}/> Made for your feed</span><span>Credits only for what you create</span></div></div><div className="hero-gallery">{[second,first,third].filter(Boolean).map((t,i)=><a className={'hero-poster poster-'+i} key={t.id} href={'/template/'+t.slug}><img src={t.thumbnail} alt={t.name}/><span className="poster-play"><Play size={18} fill="currentColor"/></span><div className="poster-caption"><span>{t.category}</span><strong>{t.name}</strong><small>{credits(t.creditCost)}{approxPrice(t.creditCost,data.creditRef)&&<em className="approx"> · {approxPrice(t.creditCost,data.creditRef)}</em>}</small></div></a>)}<span className="hero-sticker"><Sparkles size={16}/> Yes, that’s you.</span></div></section>}
 <section id="templates" className="discovery"><div className="section-heading"><div><span className="eyebrow">PICK YOUR POSSIBILITY</span><h2>{route==='/'?'A whole new you. One template away.':route==='/favorites'?'Your saved possibilities.':'Find your next main character moment.'}</h2></div><label className="search-field"><Search size={18}/><input aria-label="Search templates" placeholder="Search templates..." value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="discovery-controls"><div className="category-strip">{categories.map(c=><button className={category===c?'chip selected':'chip'} onClick={()=>setCategory(c)} key={c}>{c===ALL_CATEGORIES&&<Layers size={15}/>} {c}</button>)}</div><Select value={sort} onValueChange={v=>setSort(v as Sort)}><SelectTrigger aria-label="Sort templates"><SelectValue/></SelectTrigger><SelectContent>{sortOptions.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className="browse-meta"><span>{shown.length} possibilities, made for you</span><div>{tagOptions.map(([v,label])=><button key={v} className={flag===v?'active':''} onClick={()=>setFlag(v)}>{label}</button>)}</div></div><div className="template-grid">{shown.map(t=><article className="template-card" key={t.id}><button className={'favorite-button '+(favoriteIds.includes(t.id)?'saved':'')} aria-label={(favoriteIds.includes(t.id)?'Unsave ':'Save ')+t.name} onClick={()=>onFavorite(t.id)}><Heart size={17} fill={favoriteIds.includes(t.id)?'currentColor':'none'}/></button><a className="card-image" href={'/template/'+t.slug}><img src={t.thumbnail} alt={t.name} loading="lazy"/>{(t.trending||t.isNew)&&<span className={'card-badge '+(t.isNew&&!t.trending?'new':'')}>{t.trending?<><Flame size={13}/> Trending</>:'New'}</span>}<span className="card-duration"><Play size={11} fill="currentColor"/> {t.duration}s</span><span className="card-hover">Make it yours <ArrowUpRight size={17}/></span></a><div className="card-description"><a href={'/template/'+t.slug}><h3>{t.name}</h3><p>{t.category} <span>·</span> {t.requiredImageCount} photo{t.requiredImageCount>1?'s':''}</p></a><strong>{credits(t.creditCost)}{approxPrice(t.creditCost,data.creditRef)&&<em className="card-approx">{approxPrice(t.creditCost,data.creditRef)}</em>}</strong></div></article>)}</div>{shown.length===0&&<div className="empty-state"><Search/><h3>No templates found</h3><p>Try a different word or category.</p><button className="button secondary" onClick={()=>{setSearch('');setCategory(ALL_CATEGORIES);setFlag('all')}}>Clear filters</button></div>}</section>
 {route==='/'&&<><section className="how-it-works"><div><span className="eyebrow">FROM PHOTO TO MAIN CHARACTER</span><h2>A few taps.<br/>A whole new story.</h2></div>{[['01','Find your look','Choose the scene you want to step into.'],['02','Add your photo','A clear photo is all you need to start.'],['03','Make it yours','Spend the credits shown. Your video arrives in My creations.']].map(([n,h,p])=><div className="how-step" key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p></div>)}</section><section className="closing-cta"><Sparkles/><h2>What will you become next?</h2><a href="/explore" className="button primary">Explore all templates <ArrowRight size={18}/></a></section></>}
</>;
}
