'use client';
import {useEffect,useState} from 'react';
import {Layers,Plus,UserRound,Menu,Compass,Film,Heart,ArrowUpRight,type LucideIcon} from 'lucide-react';
import {toast} from 'sonner';
import {Toaster} from '@/components/ui/sonner';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import type {PublicTemplate,StudioUser} from '@/lib/contracts';
import Discovery from './discovery';
import TemplateDetail from './template-detail';
import AuthPage,{SignInGate} from './auth';
import Admin from './admin';
import {Checkout,Creations,Orders,Account,LegalPage} from './account-pages';
import {api,AccountNav,ErrorBox} from './shared';
export type PageData={templates:PublicTemplate[];selectedTemplate:PublicTemplate|null;user:StudioUser|null;demo:boolean;favoriteIds:string[];purchasingAvailable:boolean;registrationAvailable:boolean;error?:string};
export default function Studio({route,query,...data}:PageData&{route:string;query:Record<string,string|undefined>}){
 const [favorites,setFavorites]=useState(data.favoriteIds);const admin=route.startsWith('/admin');const protectedPage=['/creations','/favorites','/orders','/account','/checkout'].some(p=>route.startsWith(p));
 async function favorite(id:string){if(!data.user){window.location.assign('/login?next='+encodeURIComponent(route));return}try{const r=await api<{saved:boolean}>('favorites','POST',{templateId:id});setFavorites(prev=>r.saved?[...new Set([...prev,id])]:prev.filter(x=>x!==id));toast.success(r.saved?'Saved to your favorites':'Removed from favorites')}catch(e){toast.error((e as Error).message)}}
 useEffect(()=>{if(route==='/'&&data.user)void api('analytics','POST',{name:'homepage_view'}).catch(()=>{})},[route,data.user]);
 return <>{!admin&&<header className="site-header"><a className="brand" href="/"><span className="brand-symbol"><Layers size={21}/></span>PROJECT <b>STUDIO</b></a><nav><a className={route==='/'||route==='/explore'?'active':''} href="/explore">Explore</a><a className={route==='/creations'?'active':''} href="/creations">My creations</a><a className={route==='/favorites'?'active':''} href="/favorites">Favorites</a></nav><div className="header-actions">{data.demo&&<span className="demo-badge">Demo studio</span>}<a className="icon-button" href={data.user?'/account':'/login'} aria-label="Your account">{data.user?<span className="avatar small-avatar">{data.user.name[0]}</span>:<UserRound size={20}/>}</a><a className="button primary small header-create" href="/explore">Create a video <Plus size={16}/></a><Sheet><SheetTrigger asChild><button className="icon-button mobile-menu" aria-label="Open navigation menu"><Menu size={22}/></button></SheetTrigger><SheetContent><SheetHeader><SheetTitle>PROJECT STUDIO</SheetTitle><SheetDescription>Your next creation is waiting.</SheetDescription></SheetHeader><nav className="mobile-sheet-nav">{[['/explore','Explore templates'],['/creations','My creations'],['/favorites','Favorites'],['/orders','Orders'],['/account','Account'],...(data.user?.role==='admin'?[['/admin','Studio admin']]:[])].map(([href,label])=><a href={href} key={href}>{label}<ArrowUpRight size={18}/></a>)}</nav></SheetContent></Sheet></div></header>}
 {admin?<Admin route={route} query={query} user={data.user} demo={data.demo}/>:<main className={'page-shell '+(route.startsWith('/template/')?'detail-shell':'')}>{data.error?<ErrorBox message={data.error} retry={()=>window.location.reload()}/>:protectedPage&&!data.user?<SignInGate next={route}/>:route.startsWith('/template/')&&data.selectedTemplate?<TemplateDetail template={data.selectedTemplate} purchasingAvailable={data.purchasingAvailable} user={data.user} demo={data.demo} favorite={favorites.includes(data.selectedTemplate.id)} onFavorite={()=>favorite(data.selectedTemplate!.id)}/>:route==='/creations'?<Creations demo={data.demo}/>:route==='/orders'?<Orders/>:route==='/account'&&data.user?<Account user={data.user}/>:route.startsWith('/checkout/')?<Checkout id={route.split('/')[2]} demo={data.demo} query={query}/>:['/login','/register','/forgot-password','/reset-password','/verify'].includes(route)?<AuthPage route={route} query={query} demo={data.demo} registrationAvailable={data.registrationAvailable}/>:route==='/privacy'||route==='/terms'?<LegalPage type={route==='/privacy'?'privacy':'terms'}/>:<>{route==='/favorites'&&<AccountNav route={route}/>}<Discovery route={route} query={query} data={{templates:route==='/favorites'?data.templates.filter(t=>favorites.includes(t.id)):data.templates}} favoriteIds={favorites} onFavorite={favorite}/></>}</main>}
 {!admin&&<><footer><a className="brand" href="/">PROJECT <b>STUDIO</b></a><p>A little imagination looks good on you.</p><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/admin">Studio admin</a></div></footer><nav className="mobile-bottom-nav">{([['/explore','Explore',Compass],['/creations','Creations',Film],['/favorites','Favorites',Heart],['/account','Account',UserRound]] as [string,string,LucideIcon][]).map(([href,label,Icon])=><a key={href} href={href} className={route===href||href==='/explore'&&route==='/'?'active':''}><Icon size={20}/><span>{label}</span></a>)}</nav></>}<Toaster richColors position="bottom-right"/></>;
}
